search/urls.py
from django.urls import path

from search import views

app_name = 'search'

urlpatterns = [
    path('', views.home, name='home'),
    path('all', views.all, name='all'),
    path('search', views.search, name='search'),
    path('upload', views.upload, name='upload'),
    path('delete/<uuid:pk>', views.delete, name='delete'),
    path('detail/<uuid:pk>', views.detail, name='detail'),
]

searchImages/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from authentication.forms import LoginForm, MyPasswordResetForm, MySetPasswordForm, MyPasswordChangeForm
from searchImages import settings

urlpatterns = [
    path('', include('authentication.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html',
                                                         authentication_form=LoginForm,
                                                         redirect_authenticated_user='/')),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        form_class=MyPasswordResetForm, html_email_template_name='registration/password_reset_email.html')),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(form_class=MySetPasswordForm)),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',
                                               form_class=MyPasswordChangeForm)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/models.py
import uuid

from django.db import models
from django.template.defaultfilters import slugify
from sorl.thumbnail import ImageField

# Create your models here.
class Image(models.Model):
    unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField('Название изображения', max_length=255)
    slug = models.SlugField(max_length=200, blank=True)
    image = ImageField('Изображение', null=True, upload_to='')
    description = models.CharField('Описание', max_length=255, blank=True, null=True)
    height = models.IntegerField('Высота', blank=True, null=True)
    width = models.IntegerField('Ширина', blank=True, null=True)
    details = models.JSONField('Данные о сегментации изображения', null=True)
    histogram = models.JSONField('Гистограмма в JSON формате', null=True)
    created = models.DateField(auto_now_add=True, db_index=True, null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            super(Image, self).save(*args, **kwargs)
        else:
            super(Image, self).save(*args, **kwargs)

search/forms.py
from django import forms
from django.template.defaultfilters import slugify

from search.models import Image


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'image')
        widgets = {'title': forms.TextInput(attrs={'class': 'form-control'}),
                   'image': forms.FileInput(attrs={'class': 'form-control-file'})}

search/views.py
import json

import PIL
import cv2
import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from sorl.thumbnail import get_thumbnail

from search import utils, yolo, NUM_CLASS
from search.forms import ImageForm
from search.models import Image
from search.utils import generate_positional_grid_1d, get_positional_grid_1d, \
    create_position_mask, create_object_mask, create_histogram
from search.yolo3.utils import detect_image, np


def remap_keys(mapping):
    return [{str(k): v} for k, v in mapping.items()]


# Преобразование кода объекта в его название
def editLabels(label):
    pos = label.split(',')[0].replace("'", '').replace('(', '')
    obj = NUM_CLASS[int(label.split(',')[1].replace(')', '').replace("'", ''))]
    return f"{pos}, {obj}"


# Подготовка JSON файлов для отправки в ChartJS
def formationHistogram(histogram):
    hist = json.loads(histogram)
    labels = list(map(lambda x: editLabels(list(x.keys())[0]), hist))
    data = list(map(lambda x: list(x.values())[0], hist))
    return {'type': 'bar',
            'data': {
                'labels': labels,
                'datasets': [{
                    'label': 'Значение гистограммы',
                    'data': data,
                    'backgroundColor': ['rgba(153, 102, 255, 0.2)'] * len(data),
                    'borderColor': ['rgba(153, 102, 255, 1)'] * len(data),
                    'borderWidth': 1
                }]},
            'options': {'scales': {'yAxes': [{'ticks': {'beginAtZero': True}}]}}}


grid_1d = utils.generate_positional_grid_1d(5, 5)


def home(request):
    return render(request, 'search/home.html')


@login_required
def all(request):
    form = ImageForm()
    images = Image.objects.all().order_by('title')
    paginator = Paginator(images, 8)
    pageNumber = request.GET.get('page')
    currentPage = paginator.get_page(pageNumber)
    return render(request, 'search/all.html', {'images': currentPage, 'form': form})


@login_required
def search(request):
    try:
        query = request.GET['query']
    except:
        return HttpResponse(status=400)
    if query == '':
        messages.add_message(request, messages.WARNING, "Введите поисковый запрос!")
        paginator = Paginator([], 3)
        pageNumber = request.GET.get('page')
        currentPage = paginator.get_page(pageNumber)
        return render(request, 'search/search.html', {'query': query, 'images': currentPage})
    searchRequest = requests.get('http://histogram:8080/search', data=query)
    if searchRequest.status_code == 200:
        sortedTuples = sorted(searchRequest.json().items(), key=lambda item: item[1], reverse=True)
        response = {k: v for k, v in sortedTuples}

        images = []
        for img in response.items():
            try:
                images.append({'pk': img[0], 'result': round(img[1], 2), 'image': Image.objects.get(pk=img[0]).image,
                                     'title': Image.objects.get(pk=img[0]).title,
                                     'graph': json.dumps(formationHistogram(Image.objects.get(pk=img[0]).histogram))})
            except Image.DoesNotExist:
                pass
        paginator = Paginator(images, 3)
        pageNumber = request.GET.get('page')
        currentPage = paginator.get_page(pageNumber)
        return render(request, 'search/search.html', {'query': query, 'images': currentPage})
    else:
        return HttpResponse(status=404)


@login_required
def upload(request):
    # try:
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            img = form.save()
            image = Image.objects.get(pk=img.pk)
            npImage = np.fromfile(image.image, np.uint8)
            dataImage = detect_image(yolo, cv2.imdecode(npImage, cv2.IMREAD_COLOR))
            print(dataImage)
            #dataImage = segmentObjectDetections(PIL.Image.open(image.image))
            grid = generate_positional_grid_1d(5, 5)
            position_elements = get_positional_grid_1d(dataImage['width'], dataImage['height'], grid)
            pos_mask = create_position_mask(dataImage['width'], dataImage['height'], position_elements)
            obj_mask = create_object_mask(dataImage['width'], dataImage['height'], dataImage['segments'])
            histogram = json.dumps(
                remap_keys(create_histogram(dataImage['width'], dataImage['height'], pos_mask, obj_mask).to_dict()))

            img.width = dataImage['width']
            img.height = dataImage['height']
            img.details = dataImage['segments']
            img.histogram = histogram
            sendHist = requests.post('http://histogram:8080/addHistogram/' + str(image.pk),
                                     json=json.loads(histogram))
            if sendHist.status_code != 200:
                messages.add_message(request, messages.WARNING,
                                     'Ошибка при индексации в Lucene. Изображение не добавлено')
            img.save()
            return redirect('search:all')
    # except:
    #     messages.add_message(request, messages.WARNING, 'Ошибка при добавлении изображения')
    #     return redirect('search:all')
    return HttpResponse(status=400)


@login_required
def delete(request, pk):
    if Image.objects.filter(pk=pk).exists():
        img = Image.objects.get(pk=pk)
        from sorl.thumbnail import delete
        deleteHist = requests.get('http://histogram:8080/deleteHistogram/' + str(img.pk))
        if deleteHist.status_code == 200:
            delete(img.image)
            img.delete()
        else:
            messages.add_message(request, messages.WARNING, 'Ошибка удаления в Lucene. Изображение не удалено')
        return redirect('search:all')
    return HttpResponse(status=204)


@login_required
def detail(request, pk):
    if Image.objects.filter(pk=pk).exists():
        img = Image.objects.get(pk=pk)
        im = get_thumbnail(img.image, '300x300', crop='center', quality=99)
        return JsonResponse({'img': {'url': im.url, 'width': im.width, 'height': im.height},
                             'graph': formationHistogram(img.histogram)}, safe=False)
    return HttpResponse(status=204)

search/templates/search/all.html
{% extends 'application.html' %}
{% block title %}Все изображения{% endblock %}
{% block content %}
    <script>
        $(document).ready(function () {
            $('#Modal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget)
                var recipient = button.data('whatever')
                var pk = button.data('store-id')
                var modal = $(this)
                modal.find('#ModalLabel').text(recipient)
                $('#deleteButton').attr('href', 'delete/' + pk)
                $('#ChartHistogram').remove()
                $('#graphHistogram').append('<canvas id="ChartHistogram"><canvas>');
                canvas = document.querySelector('#ChartHistogram');
                ctx = canvas.getContext('2d');
                $.ajax("/detail/" + pk, {
                    statusCode: {
                        200: function (data) {
                            graphStates = new Chart(ctx, data.graph);
                            var modalImg = $('#modalImg')
                            modalImg.attr('src', data.img.url)
                        }
                    }
                })
            })
        })
    </script>
    {% load thumbnail %}
    <div class="container">
        <div class="card text-center mt-4" style="background-color:#007bff;cursor:pointer;color:white">
            <div class="card-body" href="#addImage" data-toggle="collapse" aria-controls="addImage"
                 aria-expanded="false" style="display:flex;align-items:center;justify-content:space-evenly">
                <i class="material-icons">add</i>Добавить изображение
            </div>
        </div>
        <div class="card mt-4 collapse" id="addImage">
            <div class="card-body">
                <form method="post" action="{% url 'search:upload' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form }}
                    </div>
                    {% for error in form.non_field_errors %}
                        <small class="text-danger">{{ error }}</small>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Загрузить в БД</button>
                </form>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-4 mt-4">
            {% for img in images %}
                <div class="col mb-4">
                    <div class="card">
                        {% thumbnail img.image "150x150" crop="center" as im %}
                            <img class="card-img-top" src="{{ STATIC_URL }}{{ im.url }}" alt="" style="object-fit: cover">
                        {% endthumbnail %}
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ img.title }}
                                <span class="material-icons" data-toggle="modal" data-target="#Modal"
                                      title="Информация об изображении" style="cursor: pointer;"
                                      data-whatever="{{ img.title }}" data-store-id="{{ img.pk }}">info</span>
                            </h5>
                            <p class="card-text"></p>
                            <a href="{% url 'search:delete' img.pk %}" data-me class="card-link">Удалить</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if images.number == 1 %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ images.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% if images.previous_page_number >= 1 %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ images.previous_page_number }}"
                           aria-label="{{ images.previous_page_number }}">
                            <span aria-hidden="true">{{ images.previous_page_number }}</span>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ images.number }}">
                        {{ images.number }} <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% if images.next_page_number <= images.paginator.num_pages %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ images.next_page_number }}"
                           aria-label="{{ images.next_page_number }}">
                            <span aria-hidden="true">{{ images.next_page_number }}</span>
                        </a>
                    </li>
                {% endif %}
                {% if images.number == images.paginator.num_pages %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ images.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <img id="modalImg" src="" alt="">
                        </div>
                        <div class="col" id="graphHistogram">
                            <canvas id="ChartHistogram"></canvas>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger" id="deleteButton">Удалить</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

search/templates/search/delete.html
{% extends 'application.html' %}
{% block title %}Главная страница{% endblock %}
{% block content %}
    <div class="fullscreen__container" style="flex: 1; display: flex; justify-content: center; align-items: center">
        <div class="container">
            <div class="jumbotron">
                <div class="jumbotron">
                    <h1 class="display-4">Удаление изображений</h1>
                    <hr class="my-4">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Введите образы для поиска"
                               aria-label="Введите образы для поиска" aria-describedby="button-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="button-addon2">Поиск
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

search/templates/search/home.html
{% extends 'application.html' %}
{% block title %}Главная страница{% endblock %}
{% block content %}
    <div class="fullscreen__container" style="flex: 1; display: flex; justify-content: center; align-items: center">
        <div class="container">
            <div class="jumbotron">
                <div class="jumbotron">
                    <h1 class="display-4">Поиск изображений</h1>
                    <p class="lead">Выпускная квалификационная работа магистра</p>
                    <hr class="my-4">
                    {% if user.is_authenticated %}
                        <form action="{% url 'search:search' %}">
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Введите текст для поиска"
                                       name="query" aria-label="Введите текст для поиска"
                                       aria-describedby="button-addon2"
                                       id="query">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Поиск
                                    </button>
                                </div>
                            </div>
                        </form>
                    {% else %}
                        <p class="lead">Для проверки работы приложения необходимо войти в систему.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

search/templates/search/search.html
{% extends 'application.html' %}
{% block title %}Результаты поиска{% endblock %}
{% block content %}
    <script>
        $(document).ready(function () {
            for (i = 0; i < document.getElementsByClassName('ChartHistogram').length; i++) {
                var graph = document.getElementsByClassName('ChartHistogram')[i].getContext('2d');
                var data = JSON.parse(document.getElementsByClassName('dataChart')[i].value)
                var graphStates = new Chart(graph, data);
            }
        })
    </script>
    {% load thumbnail %}
    <div class="container">
        <div class="">
            <div class="card-body">
                <form action="{% url 'search:search' %}">
                    <div class="input-group mb-1">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="material-icons">image</i></span>
                        </div>
                        <input type="text" name="query" class="form-control" placeholder="Введите поисковый запрос"
                               id="search"
                               aria-label="Введите поисковый запрос" aria-describedby="searchButton"
                               autocapitalize="words"
                               value="{{ query }}">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit" id="searchButton">Поиск</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if images.number == 1 %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ images.previous_page_number }}&query={{ query | urlencode }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% if images.previous_page_number >= 1 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ images.previous_page_number }}&query={{ query | urlencode }}"
                           aria-label="{{ images.previous_page_number }}">
                            <span aria-hidden="true">{{ images.previous_page_number }}</span>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ images.number }}&query={{ query | urlencode }}">
                        {{ images.number }} <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% if images.next_page_number <= images.paginator.num_pages %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ images.next_page_number }}&query={{ query | urlencode }}"
                           aria-label="{{ images.next_page_number }}">
                            <span aria-hidden="true">{{ images.next_page_number }}</span>
                        </a>
                    </li>
                {% endif %}
                {% if images.number == images.paginator.num_pages %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ images.next_page_number }}&query={{ query | urlencode }}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <div class="card-body">
            {% for img in images %}
                <div class="card mb-1">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-3 col-sm-2 col-md-3 col-lg-2 col-xl-2 text-center">
                                {% thumbnail img.image "150x150" crop="center" as im %}
                                    <img class="card-img-top" src="{{ STATIC_URL }}{{ im.url }}" width="{{ im.width }}"
                                         height="{{ im.height }}" alt="">
                                {% endthumbnail %}
                            </div>
                            <div class="col-9 col-sm-3 col-md-9 col-lg-7 col-xl-5">
                                <b>Совпадение: {{ img.result }}%</b><br><small
                                    class="text-muted">{{ img.title }}</small></div>
                            <div class="d-none d-sm-block col-sm-7 d-md-none d-lg-block col-lg-3 col-xl-5 text-center">
                                <canvas class="ChartHistogram" data-store-id="{{ img.pk }}"></canvas>
                                <input type="hidden" class="dataChart" value="{{ img.graph }}">
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}