authentication/urls.py
from django.urls import path

from authentication import views

app_name = 'authentication'
urlpatterns = [
    path('accounts/registration/', views.registration, name='registration'),
    path('accounts/editProfile/', views.editProfile, name='editProfile'),
    path('accounts/password_change/done/', views.passwordDone, name='passwordDone'),
    path('accounts/reset/done/', views.resetDone, name='resetDone'),
    path('activate/<str:uidb64>/<str:token>', views.activate, name='activate'),
]

search/urls.py
from django.urls import path

from search import views

app_name = 'search'

urlpatterns = [
    path('', views.home, name='home'),
    path('all', views.all, name='all'),
    path('search', views.search, name='search'),
    path('upload', views.upload, name='upload'),
    path('delete/<uuid:pk>', views.delete, name='delete'),
    path('detail/<uuid:pk>', views.detail, name='detail'),
]

searchImages/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from authentication.forms import LoginForm, MyPasswordResetForm, MySetPasswordForm, MyPasswordChangeForm
from searchImages import settings

urlpatterns = [
    path('', include('authentication.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html',
                                                         authentication_form=LoginForm,
                                                         redirect_authenticated_user='/')),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        form_class=MyPasswordResetForm, html_email_template_name='registration/password_reset_email.html')),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(form_class=MySetPasswordForm)),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',
                                               form_class=MyPasswordChangeForm)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/application.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <meta charset="UTF-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"
            integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="
            crossorigin="anonymous"></script>

    <script src="{% static 'js/applications.js' %}"></script>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1"/>
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <title>{% block title %}{% endblock %} </title>
</head>
<body style="min-height: 100vh; display: flex; flex-direction: column">
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">
    <a class="navbar-brand" href="/">Поиск изображений</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_superuser %}
                <a class="nav-link" href="/admin">Администрирование</a>
                <a class="nav-link" href="{% url 'search:all' %}">Все изображения</a>
            {% elif request.user.is_staff %}
                <a class="nav-link" href="{% url 'search:all' %}">Все изображения</a>
            {% endif %}
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if request.user.is_authenticated %}
                    <a class="nav-link" href="{% url 'authentication:editProfile' %}">{{ request.user.username }}</a>
                {% else %}
                    <a class="nav-link" href="{% url 'login' %}">Вход</a>
                {% endif %}
            </li>
            <li class="nav-item">
                {% if request.user.is_authenticated %}
                    <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                {% else %}
                    <a class="nav-link" href="{% url 'authentication:registration' %}">Регистрация</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>
{% if messages %}
    <div class="alert alert-light alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">Сообщения</h4>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <ul class="list-group messages">
            {% for message in messages %}
                <li
                        {% if message.tags %}
                            class="list-group-item list-group-item-{{ message.tags }}" {% endif %}>{{ message|safe }}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
{% block content %}{% endblock %}
</body>
</html>